In [1]:
using Plots
plot(rand(3,3))
contour(-2:2, -2:2, (x,y)->x^2 + y^2)
nothing

┌ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
└ @ Base loading.jl:1278


In [3]:
A = [
    1.0 1.0 1.0 0 0;
    -1.0 1.0 0 1.0 0;
    2.0 -1.0 0 0 1.0
]
b = [3.0; 2.0; 4.0]
c = [-3.0; -1.0; 0; 0; 0]

5-element Array{Float64,1}:
 -3.0
 -1.0
  0.0
  0.0
  0.0

In [71]:
m, n = size(A)
IB = [2, 4, 1]
B = A[:,IB]
IN = setdiff(1:size(A,2), IB)
N = A[:,IN]

3×2 Array{Float64,2}:
 1.0  0.0
 0.0  0.0
 0.0  1.0

In [72]:
xB = B \ b
y = B' \ c[IB]
cNbarra = c[IN] - N' * y
xB, cNbarra

([0.6666666666666665, 3.666666666666667, 2.3333333333333335], [1.6666666666666665, 0.6666666666666666])

In [73]:
using LinearAlgebra
M1 = [1 -c[IB]'; zeros(m) Matrix(I, m, m)]
M2 = [1 zeros(m)'; zeros(m) inv(B)]

M1 * M2 * [c' 0; A b]

4×6 Array{Float64,2}:
  0.0          1.11022e-16   1.66667   0.0   0.666667  7.66667
  1.11022e-16  1.0           0.666667  0.0  -0.333333  0.666667
 -2.22045e-16  0.0          -0.333333  1.0   0.666667  3.66667
  1.0          0.0           0.333333  0.0   0.333333  2.33333

In [76]:
11/3

3.6666666666666665